required = [
    "github.com/spf13/cobra",
    "github.com/spf13/pflag",
    "github.com/satori/go.uuid",
    "go.uber.org/zap",
    "github.com/coreos/etcd",
    "github.com/pelletier/go-toml",
    "github.com/gorilla/mux",
    "github.com/gorilla/websocket",
]

[[constraint]]
name = "github.com/spf13/cobra"
version = "^0.0.3"

[[constraint]]
name = "github.com/spf13/pflag"
version = "^1.0.2"

[[constraint]]
name = "github.com/satori/go.uuid"
version = "^1.2.0"

[[constraint]]
name = "go.uber.org/zap"
version = "^1.9.1"

[[constraint]]
name = "github.com/coreos/etcd"
version = "^3.3.9"

[[constraint]]
name = "github.com/pelletier/go-toml"
version = "^1.2.0"

[[constraint]]
name = "github.com/gorilla/mux"
version = "^1.6.2"

[[constraint]]
name = "github.com/gorilla/websocket"
version = "^1.3.0"